// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reported.Persistence;

#nullable disable

namespace Reported.Persistence.Migrations
{
    [DbContext(typeof(ReportedDbContext))]
    [Migration("20260214210932_AddAppealRecord")]
    partial class AddAppealRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Reported.Persistence.AppealRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppealAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppealWins")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("AppealRecord");
                });

            modelBuilder.Entity("Reported.Persistence.UserReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Confused")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InitiatedDiscordName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("InitiatedUserDiscordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId");

                    b.ToTable("UserReport");
                });
#pragma warning restore 612, 618
        }
    }
}
